# Generated by Django 3.2 on 2024-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0003_auto_20240515_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.CharField(max_length=100)),
                ('rut_prestador', models.CharField(max_length=10)),
                ('num_boleta', models.IntegerField()),
                ('fecha_boleta', models.DateField()),
                ('monto_bruto', models.IntegerField()),
                ('detalle_boleta', models.CharField(max_length=500)),
                ('detalle_analista', models.CharField(max_length=500)),
                ('CeCo', models.IntegerField()),
                ('escuela', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_escuela', models.CharField(max_length=20)),
                ('nombre_escuela', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prestadorServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('DV', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido1', models.CharField(max_length=40)),
                ('apellido2', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('id_banco', models.IntegerField()),
                ('tipo_cuenta', models.CharField(max_length=30)),
                ('numero_cuenta', models.IntegerField()),
            ],
        ),
    ]
