# Generated by Django 3.2 on 2024-05-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0004_banco_documento_escuela_prestadorservicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceco',
            name='anno_contable',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='escuela',
        ),
        migrations.AddField(
            model_name='ceco',
            name='fecha_fin',
            field=models.DateField(default='01012024'),
        ),
        migrations.AddField(
            model_name='ceco',
            name='fecha_inicio',
            field=models.DateField(default='01012024'),
        ),
    ]
