# Generated by Django 3.2 on 2024-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0005_auto_20240525_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestadorservicios',
            old_name='DV',
            new_name='DVPrestador',
        ),
        migrations.RenameField(
            model_name='prestadorservicios',
            old_name='apellido1',
            new_name='apellido1Prestador',
        ),
        migrations.RenameField(
            model_name='prestadorservicios',
            old_name='apellido2',
            new_name='apellido2Prestador',
        ),
        migrations.RenameField(
            model_name='prestadorservicios',
            old_name='correo',
            new_name='correoPrestador',
        ),
        migrations.RenameField(
            model_name='prestadorservicios',
            old_name='nombre',
            new_name='nombrePrestador',
        ),
        migrations.RenameField(
            model_name='prestadorservicios',
            old_name='rut',
            new_name='rutPrestador',
        ),
        migrations.AlterField(
            model_name='ceco',
            name='fecha_fin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ceco',
            name='fecha_inicio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ceco',
            name='nombre_CeCo',
            field=models.CharField(max_length=40),
        ),
    ]
